export enum MOVIE_GENRE {
  ACTION = "ACTION",
  COMEDY = "COMEDY",
  DRAMA = "DRAMA",
  FANTASY = "FANTASY",
  HORROR = "HORROR",
  MYSTERY = "MYSTERY",
  ROMANCE = "ROMANCE",
  THRILLER = "THRILLER",
  WESTERN = "WESTERN",
}
